/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import model.Profile;

/**
 *
 * @author TT
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Profile profile;
    
            
    public CreateJPanel(Profile profile) {
        initComponents();
        this.profile = profile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtFimage = new javax.swing.JTextField();
        btnFimage = new javax.swing.JButton();
        lblFaceImg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBirthDate = new javax.swing.JLabel();
        txtBirthDate = new javax.swing.JTextField();
        lblBirthDateRequire = new javax.swing.JLabel();
        lblTeleNum = new javax.swing.JLabel();
        txtTeleNum = new javax.swing.JTextField();
        lblTeleNumRequire = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblSSNRequire = new javax.swing.JLabel();
        lblGeoData = new javax.swing.JLabel();
        txtStreetName = new javax.swing.JTextField();
        lblStreetName = new javax.swing.JLabel();
        txtZipcode = new javax.swing.JTextField();
        lblZipcode = new javax.swing.JLabel();
        lblZipcodeRequire1 = new javax.swing.JLabel();
        lblBankAccount = new javax.swing.JLabel();
        txtBankAccount = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtLinkedin = new javax.swing.JTextField();
        lblLinkedin = new javax.swing.JLabel();
        txtFaxNum = new javax.swing.JTextField();
        lblFaxNum = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        lblMRN = new javax.swing.JLabel();
        txtHPBN = new javax.swing.JTextField();
        lblHPBN = new javax.swing.JLabel();
        txtCertiNum = new javax.swing.JTextField();
        lblCertiNum = new javax.swing.JLabel();
        txtVehicleID = new javax.swing.JTextField();
        lblVehicleID = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        lblIP = new javax.swing.JLabel();
        lblBankAccoRequire2 = new javax.swing.JLabel();
        lblLinkedinRequire = new javax.swing.JLabel();
        lblMRNRequire = new javax.swing.JLabel();
        lblFaxNUmRequire = new javax.swing.JLabel();
        lblVehivleIDRequire = new javax.swing.JLabel();
        lblIPRequire = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Person Profile");

        lblName.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name:");

        btnSave.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        btnSave.setText("Save All");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnFimage.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnFimage.setText("Choose Image");
        btnFimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFimageActionPerformed(evt);
            }
        });

        lblFaceImg.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblFaceImg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFaceImg.setText("Face Image:");

        jLabel1.setText("JPG/JPEG/PNG");

        lblBirthDate.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblBirthDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBirthDate.setText("Birth Date:");

        lblBirthDateRequire.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblBirthDateRequire.setText("MM/DD/YYYY with the slash");

        lblTeleNum.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblTeleNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTeleNum.setText("Mobil Number:");

        lblTeleNumRequire.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblTeleNumRequire.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTeleNumRequire.setText("+1");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel2.setText("US 10 digits e.g. 1234567899");

        lblSSN.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSSN.setText("SSN:");

        lblSSNRequire.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblSSNRequire.setText("last 4 digits");

        lblGeoData.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblGeoData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGeoData.setText("Address:");

        lblStreetName.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblStreetName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStreetName.setText("Street Name");

        lblZipcode.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblZipcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZipcode.setText("Zip Code");

        lblZipcodeRequire1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblZipcodeRequire1.setText("5 digits number");

        lblBankAccount.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblBankAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBankAccount.setText("Bank Account:");

        lblEmail.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email:");

        lblLinkedin.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblLinkedin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLinkedin.setText("Linkedin");

        lblFaxNum.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblFaxNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFaxNum.setText("Fax Number:");

        lblMRN.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblMRN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMRN.setText("MRN:");

        lblHPBN.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblHPBN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHPBN.setText("HPBN:");

        lblCertiNum.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblCertiNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCertiNum.setText("Certi Num:");

        lblVehicleID.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblVehicleID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVehicleID.setText("Vehicle ID:");

        lblIP.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblIP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIP.setText("IP:");

        lblBankAccoRequire2.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblBankAccoRequire2.setText("16 digits number");

        lblLinkedinRequire.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblLinkedinRequire.setText("Mobile Phone Number or Email Address");

        lblMRNRequire.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblMRNRequire.setText("7 digits number");

        lblFaxNUmRequire.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblFaxNUmRequire.setText("10 digits number");

        lblVehivleIDRequire.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblVehivleIDRequire.setText("17 chars");

        lblIPRequire.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lblIPRequire.setText("xxx.xxx.xxx.xxx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTeleNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTeleNumRequire)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtName)
                                                    .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblBirthDateRequire))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblSSNRequire))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblZipcode)
                                                    .addComponent(lblStreetName))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblZipcodeRequire1))
                                                    .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblBankAccoRequire2)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtLinkedin)
                                            .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLinkedinRequire)
                                            .addComponent(lblFaxNUmRequire))))
                                .addGap(0, 78, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMRNRequire))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblIP, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblIPRequire))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnFimage)
                                                    .addComponent(txtFimage, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(lblVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(txtVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addComponent(lblHPBN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(lblCertiNum, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtHPBN)
                                            .addComponent(txtCertiNum, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVehivleIDRequire)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFaceImg, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(692, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBirthDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBirthDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirthDateRequire, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeleNumRequire)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblSSNRequire)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStreetName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZipcode)
                            .addComponent(lblZipcodeRequire1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBankAccoRequire2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkedinRequire))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaxNUmRequire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMRNRequire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHPBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHPBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCertiNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCertiNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehivleIDRequire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIPRequire))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaceImg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFimage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFimage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        ///////////////   Name   ///////////////////////
        profile.setName(txtName.getText());
        ///////////////   Birth Date   ///////////////////////
        int t0 = 0;
        int temp = 0;
        String bd = txtBirthDate.getText();
        if(bd.length()==10){
            if((bd.charAt(2)=='/')&&(bd.charAt(5)=='/')){
                temp = Integer.valueOf(bd.substring(0, 2));
                if(0<temp && temp<13){
                    temp = Integer.valueOf(bd.substring(3, 5));
                    if(0<temp && temp<32){
                        temp = Integer.valueOf(bd.substring(6));
                        if(1900<temp && temp<2022){
                            t0 = 1; // input Birth Date valid
                        }
                    }
                }
            }
        }
        if(t0==1){
            profile.setBirthDate(txtBirthDate.getText()); // valid
        } else profile.setBirthDate(null);  // not valid
        ///////////////   Telephone Number   ///////////////////////
        int t1 = 0;
        if(txtTeleNum.getText().length() == 10){   // 10 digits 
            if(txtTeleNum.getText().charAt(0)!='0' && allNumber(txtTeleNum.getText())){    // all number, and the first number cannot be 0
                t1 = 1;
            }
        }
        if(t1 == 1){
            profile.setTeleNum(Long.valueOf(txtTeleNum.getText())); 
        } else profile.setTeleNum(0);
        ///////////////   SSN   ///////////////////////
        int t2 = 0;
        if(txtSSN.getText().length() == 4){ // 4 digits 
            if(allNumber(txtSSN.getText())){    // all number
                t2 = 1;
            }
        }
        if(t2 == 1){
            profile.setSsn(Integer.valueOf(txtSSN.getText())); 
        } else profile.setSsn(0);
        ///////////////   Address   ///////////////////////
        profile.setGeoStreet(txtStreetName.getText());
        int t3 = 0;
        if(txtZipcode.getText().length() == 5){   // 5 digits string
            if(allNumber(txtZipcode.getText())){    // all number
                t3 = 1;
            }
        }
        if(t3 == 1){
            profile.setGeoData(txtZipcode.getText()); 
        } else profile.setGeoData(null);
        ///////////////   Bank Account Number   ///////////////////////        
        int t4 = 0;
        Pattern pBankA = Pattern.compile("\\d{4}\\s?\\d{4}\\s?\\d{4}\\s?\\d{4}");  // regular expression of Email Address
        if(pBankA.matcher(txtBankAccount.getText()).matches()){   // 16 digits 
            if(txtBankAccount.getText().charAt(0)!='0'){    // all number, and the first number cannot be 0
                t4 = 1;
            }
        }
        if(t4 == 1){
            profile.setBankAccoNum(Long.valueOf(txtBankAccount.getText().replaceAll(" ", ""))); 
        } else profile.setBankAccoNum(0);
        ///////////////   Email Address   /////////////////////// 
        int t5 = 0;
        Pattern pEmail = Pattern.compile("\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*");  // regular expression of Email Address
        if(pEmail.matcher(txtEmail.getText()).matches()){    
            t5 = 1;
        }
        if(t5 == 1){
            profile.setEmailAddr(txtEmail.getText());
        } else profile.setEmailAddr(null);
        
        ///////////////   Fax Number   ///////////////////////
        int t6 = 0;
        Pattern pFax = Pattern.compile("\\d{10}");
        if(pFax.matcher(txtFaxNum.getText()).matches()){  // 10 digits number
            if(txtFaxNum.getText().charAt(0)!='0'){    
                t6 = 1;
            }
        }
        if(t6 == 1){
            profile.setFaxNum(Integer.valueOf(txtFaxNum.getText())); 
        } else profile.setFaxNum(0);
        ///////////////   MRN   ///////////////////////
        int t7 = 0;
        Pattern pMrn = Pattern.compile("\\d{7}");  // regular expression of 7 digits number
        if(pMrn.matcher(txtMRN.getText()).matches()){
                t7 = 1;
        }
        if(t7 == 1){
            profile.setMrn(Integer.valueOf(txtMRN.getText())); 
        } else profile.setMrn(0);
        
        ///////////////   Vehicle Id   ///////////////////////
        int t8 = 0;
        Pattern pVid = Pattern.compile("[A-Za-z0-9]+");  // regular expression of char and num
        if(txtVehicleID.getText().length() == 17){       // 17 digits
            if(pVid.matcher(txtVehicleID.getText()).matches()){    
                t8 = 1;
            }
        }
        if(t8 == 1){
            profile.setVehicleId(txtVehicleID.getText()); 
        } else profile.setVehicleId(null);
        ///////////////   Linkedin   ///////////////////////
        int t9 = 0;
        Pattern pLinkedin = Pattern.compile("\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*");  // regular expression of Email Address
        Pattern pLinkedinPhone = Pattern.compile("(1\\s?)?(\\(\\d{3}\\)|\\d{3})\\s?-?\\d{3}-?\\s?\\d{4}"); // regular expression of US mobile phone number
        if(pLinkedin.matcher(txtLinkedin.getText()).matches() || pLinkedinPhone.matcher(txtLinkedin.getText()).matches()){    
            t9 = 1;
        }
        if(t9 == 1){
            profile.setLinkedin(txtLinkedin.getText());
        } else profile.setLinkedin(null);
        ///////////////   IP   ///////////////////////
        int t10 = 0;
        Pattern pIP = Pattern.compile("(?:(?:1[0-9][0-9]\\.)|(?:2[0-4][0-9]\\.)|(?:25[0-5]\\.)|(?:[1-9][0-9]\\.)|(?:[0-9]\\.)){3}(?:(?:1[0-9][0-9])|(?:2[0-4][0-9])|(?:25[0-5])|(?:[1-9][0-9])|(?:[0-9]))");  // regular expression of IP Address
        if(pIP.matcher(txtIP.getText()).matches() || pIP.matcher(txtIP.getText()).matches()){    
            t10 = 1;
        }
        if(t10 == 1){
            profile.setInternetProtAddr(txtIP.getText());
        } else profile.setInternetProtAddr(null);
        ///////////////   HBPN & Certificate Number   ///////////////////////
        profile.setHpbn(txtHPBN.getText());
        profile.setCertiNum(txtCertiNum.getText());
        
        
        String state1 = "Birth Date: saved."; if(t0 == 0){state1 = "Birth Date: invalid input.";}
        String state2 = "Phone Number: saved."; if(t1 == 0){state2 = "Phone Number: invalid input.";}
        String state3 = "SSN: saved."; if(t2 == 0){state3 = "SSN: invalid input.";}
        String state4 = "Address Zipcode: saved."; if(t3 == 0){state4 = "Address Zipcode: invalid input.";}
        String state5 = "Bank Account: saved."; if(t4 == 0){state5 = "Bank Account: invalid input.";}
        String state6 = "Email: saved"; if(t5 == 0){state6 = "Email: invalid input.";}
        String state7 = "Fax: saved"; if(t6 == 0){state7 = "Fax: invalid input.";}
        String state8 = "MRN: saved."; if(t7 == 0){state8 = "MRN: invalid input.";}
        String state9 = "VehicleID: saved."; if(t8 == 0){state9 = "VehicleID: invalid input.";}
        String state10 = "Linkedin: saved."; if(t9 == 0){state10 = "Linkedin: invalid input.";}
        String state11 = "IP Adress: saved."; if(t10 == 0){state11 = "IP Adress: invalid input.";}
        
        
//        JOptionPane.showMessageDialog(this, "testState:" + '\n' + t0+t1+t2+t3+t4+t5+t6+t7+t8+t9+t10 ); 
        JOptionPane.showMessageDialog(this, "Create Your Profile" + '\n' +'\n' + state1 + '\n' + state2 + '\n' + state3 + '\n' + state4 + '\n' + state5 + '\n' + state6 + '\n' + state7 + '\n' + state8 + '\n' + state9 + '\n' + state10 + '\n' + state11  ); 
        
    }//GEN-LAST:event_btnSaveActionPerformed

    public static boolean allNumber(String str){  
        ////////////// valid input whether all numbers  //////////////////
        
        Pattern pattern = Pattern.compile("[0-9]*"); // regular expression of number
        Matcher matcher = pattern.matcher(str);  // Matcher class type
        return matcher.matches();    // 'matches()' match whole string
    } 
    
    
    private void btnFimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFimageActionPerformed
        // TODO add your handling code here:
            ////////////// input face image  //////////////////
            
        JFileChooser faceImgChooser = new JFileChooser();
        faceImgChooser.setCurrentDirectory(new File("."));//set default path as the same with the project
        faceImgChooser.setMultiSelectionEnabled(false); //no multi selection allowed
        FileFilter myfilefilter = new FileFilter(){
                        @Override
			public String getDescription(){
				return "JPG/PNG/JPEG File(*.jpg/.png/.jpeg)";
			}
                        @Override
			public boolean accept(File f){
				if(f.getName().toLowerCase().endsWith(".jpg")){
					return true;
				} else if(f.getName().toLowerCase().endsWith(".png")){
					return true;
				} else if(f.getName().toLowerCase().endsWith(".jpeg")){
					return true;
				} else return false;
			}
		};
        faceImgChooser.setFileFilter(myfilefilter); // set filefilter, only JPG/JPEG/PNG File allowed
        faceImgChooser.showOpenDialog(null);  //open default dialog
        
        File faceImg = faceImgChooser.getSelectedFile(); // store image as File
        String imagName = faceImg.getPath();
        txtFimage.setText(imagName);     // txt show face image's address info
        profile.setfImageAddr(imagName); // store face image's address
        profile.setfImage(faceImg);      // store face image 
        
    }//GEN-LAST:event_btnFimageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFimage;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBankAccoRequire2;
    private javax.swing.JLabel lblBankAccount;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblBirthDateRequire;
    private javax.swing.JLabel lblCertiNum;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaceImg;
    private javax.swing.JLabel lblFaxNUmRequire;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHPBN;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblIPRequire;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblLinkedinRequire;
    private javax.swing.JLabel lblMRN;
    private javax.swing.JLabel lblMRNRequire;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSSNRequire;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblTeleNum;
    private javax.swing.JLabel lblTeleNumRequire;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleID;
    private javax.swing.JLabel lblVehivleIDRequire;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JLabel lblZipcodeRequire1;
    private javax.swing.JTextField txtBankAccount;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtCertiNum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtFimage;
    private javax.swing.JTextField txtHPBN;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtStreetName;
    private javax.swing.JTextField txtTeleNum;
    private javax.swing.JTextField txtVehicleID;
    private javax.swing.JTextField txtZipcode;
    // End of variables declaration//GEN-END:variables



}

