/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import model.Profile;

/**
 *
 * @author TT
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    Profile profile;
    
    public DisplayJPanel(Profile profile) {
        initComponents();
        this.profile = profile;
        
        displayProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnViewFimg = new javax.swing.JButton();
        lblforimg = new javax.swing.JLabel();
        btnHideImg = new javax.swing.JButton();
        lblBirthDate = new javax.swing.JLabel();
        txtBirthDate = new javax.swing.JTextField();
        lblTeleNum = new javax.swing.JLabel();
        txtTeleNum = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblTeleNumRequire = new javax.swing.JLabel();
        lblStreetName = new javax.swing.JLabel();
        txtStreetName = new javax.swing.JTextField();
        lblZipcode = new javax.swing.JLabel();
        txtZipcode = new javax.swing.JTextField();
        txtHPBN = new javax.swing.JTextField();
        lblHPBN = new javax.swing.JLabel();
        txtCertiNum = new javax.swing.JTextField();
        lblCertiNum = new javax.swing.JLabel();
        txtBankAccount = new javax.swing.JTextField();
        txtVehicleID = new javax.swing.JTextField();
        lblVehicleID = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        lblIP = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtLinkedin = new javax.swing.JTextField();
        lblLinkedin = new javax.swing.JLabel();
        txtFaxNum = new javax.swing.JTextField();
        lblFaxNum = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        lblMRN = new javax.swing.JLabel();
        lblBankAccount = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Person Profile");

        lblName.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name:");

        txtName.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnViewFimg.setText("View Image");
        btnViewFimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFimgActionPerformed(evt);
            }
        });

        lblforimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblforimg.setText("Your Face Image");
        lblforimg.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnHideImg.setText("Hide Image");
        btnHideImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideImgActionPerformed(evt);
            }
        });

        lblBirthDate.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblBirthDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBirthDate.setText("Birth Date:");

        txtBirthDate.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        txtBirthDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthDateActionPerformed(evt);
            }
        });

        lblTeleNum.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblTeleNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTeleNum.setText("Mobil Number:");

        txtTeleNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleNumActionPerformed(evt);
            }
        });

        lblSSN.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSSN.setText("SSN:");

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        lblTeleNumRequire.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblTeleNumRequire.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTeleNumRequire.setText("+1");

        lblStreetName.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblStreetName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStreetName.setText("Address Street:");

        txtStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetNameActionPerformed(evt);
            }
        });

        lblZipcode.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblZipcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZipcode.setText("Zip code");

        txtZipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipcodeActionPerformed(evt);
            }
        });

        lblHPBN.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblHPBN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHPBN.setText("HPBN:");

        txtCertiNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertiNumActionPerformed(evt);
            }
        });

        lblCertiNum.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblCertiNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCertiNum.setText("Certi Num:");

        lblVehicleID.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblVehicleID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVehicleID.setText("Vehicle ID:");

        lblIP.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblIP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIP.setText("IP:");

        lblEmail.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email:");

        lblLinkedin.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblLinkedin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLinkedin.setText("Linkedin");

        lblFaxNum.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblFaxNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFaxNum.setText("Fax Number:");

        lblMRN.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblMRN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMRN.setText("MRN:");

        lblBankAccount.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblBankAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBankAccount.setText("Bank Account:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHPBN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCertiNum, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIP, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCertiNum)
                            .addComponent(txtHPBN)
                            .addComponent(txtMRN)
                            .addComponent(txtFaxNum)
                            .addComponent(txtVehicleID)
                            .addComponent(txtLinkedin)
                            .addComponent(txtBankAccount)
                            .addComponent(txtEmail)
                            .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnViewFimg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHideImg))
                            .addComponent(lblforimg, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(lblZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSSN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblTeleNum, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(lblTeleNumRequire)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTeleNumRequire)
                            .addComponent(txtTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblforimg, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblZipcode)
                        .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnViewFimg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHideImg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHPBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHPBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCertiNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCertiNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehicleID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHideImg, btnViewFimg});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblName, txtName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBirthDate, txtSSN, txtTeleNum});

    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnViewFimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFimgActionPerformed
        // TODO add your handling code here:
        
        BufferedImage faceImg = null;
        try {
//            faceImg = ImageIO.read(new File(profile.getfImageAddr())); // load image through address(not convenient)
            faceImg = ImageIO.read(profile.getfImage());  // load image directly 
        } catch (IOException ex) {
            Logger.getLogger(DisplayJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image resizedFaceImg = faceImg.getScaledInstance(lblforimg.getWidth(), lblforimg.getHeight(), Image.SCALE_SMOOTH); // reshape the image to fit in the label
        ImageIcon imageIcon = new ImageIcon(resizedFaceImg); 
        lblforimg.setIcon(imageIcon);                     // set label's icon
        
    }//GEN-LAST:event_btnViewFimgActionPerformed

    private void btnHideImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideImgActionPerformed
        // TODO add your handling code here:
        lblforimg.setIcon(null);  // not display the image in the label
    }//GEN-LAST:event_btnHideImgActionPerformed

    private void txtBirthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthDateActionPerformed

    private void txtTeleNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleNumActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetNameActionPerformed

    private void txtZipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipcodeActionPerformed

    private void txtCertiNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertiNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertiNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHideImg;
    private javax.swing.JButton btnViewFimg;
    private javax.swing.JLabel lblBankAccount;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblCertiNum;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblHPBN;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMRN;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblTeleNum;
    private javax.swing.JLabel lblTeleNumRequire;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleID;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JLabel lblforimg;
    private javax.swing.JTextField txtBankAccount;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtCertiNum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtHPBN;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtStreetName;
    private javax.swing.JTextField txtTeleNum;
    private javax.swing.JTextField txtVehicleID;
    private javax.swing.JTextField txtZipcode;
    // End of variables declaration//GEN-END:variables

    private void displayProfile() {
        
        int i, j;
        
        ////////// Name ///////////////
        txtName.setText(profile.getName());
        ////////// Bitrh Date ///////////////
        txtBirthDate.setText(profile.getBirthDate());
        ////////// Telephone Number ///////////////
        if(profile.getTeleNum() != 0){
            String tempTN = Long.toString(profile.getTeleNum());
            txtTeleNum.setText('(' + tempTN.substring(0, 3) + ')' + tempTN.substring(3, 6) + '-' + tempTN.substring(6));  // display as (xxx)xxx-xxxx 
        }
        ////////// SSN ///////////////
        if(profile.getSsn() != 0){
            if(Integer.toString(profile.getSsn()).charAt(0) == 0 ){
                txtSSN.setText('0' + Integer.toString(profile.getSsn()));
            } else txtSSN.setText(Integer.toString(profile.getSsn()));
            switch(Integer.toString(profile.getSsn()).length()){
                case 4: txtSSN.setText(Integer.toString(profile.getSsn())); break;
                case 3: txtSSN.setText('0' + Integer.toString(profile.getSsn())); break;
                case 2: txtSSN.setText("00" + Integer.toString(profile.getSsn())); break;
                case 1: txtSSN.setText("000" + Integer.toString(profile.getSsn())); break;   // add missing 0 in the front
                default:
            }
        }
        ////////// Address ///////////////
        txtStreetName.setText(profile.getGeoStreet());
        txtZipcode.setText(profile.getGeoData());
        ///////////////   Bank Account Number   /////////////////////// 
        if(profile.getBankAccoNum()!= 0){
            String tempBA = Long.toString(profile.getBankAccoNum());
            txtBankAccount.setText(tempBA.substring(0, 4) +' '+ tempBA.substring(4, 8) + ' ' + tempBA.substring(8, 12) + ' '+tempBA.substring(12));  // display as xxxx xxxx xxxx xxxx
        }
        ///////////////   Email Address   /////////////////////// 
        txtEmail.setText(profile.getEmailAddr());
        ///////////////   Fax Number   ///////////////////////
        if(profile.getFaxNum()!= 0){
            txtFaxNum.setText(Integer.toString(profile.getFaxNum()));
        }
        ///////////////   MRN   ///////////////////////
       String mrn = Integer.toString(profile.getMrn());
        if(profile.getMrn()!= 0){
            if(mrn.length()<10){
                j = 7-mrn.length();
                for(i=0;i<j;i++){
                    mrn = '0' + mrn;
                }
            }
            txtMRN.setText(mrn);
        }
        ///////////////   Vehicle Id   ///////////////////////
        txtVehicleID.setText(profile.getVehicleId());
        ///////////////   Linkedin   ///////////////////////
        txtLinkedin.setText(profile.getLinkedin());
        ///////////////   IP   ///////////////////////
        txtIP.setText(profile.getInternetProtAddr());
        ///////////////   HBPN & Certificate Number   ///////////////////////
        txtHPBN.setText(profile.getHpbn());
        txtCertiNum.setText(profile.getCertiNum());
       

    }
}
